#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v13
# autospec commit: dc0ff31
#
Name     : pypi-watchfiles
Version  : 0.22.0
Release  : 2
URL      : https://files.pythonhosted.org/packages/53/e1/666771f0746f95c4df767ff98ff17fe55bb0c32ac88ec14ce0615a789330/watchfiles-0.22.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/53/e1/666771f0746f95c4df767ff98ff17fe55bb0c32ac88ec14ce0615a789330/watchfiles-0.22.0.tar.gz
Source1  : http://localhost/cgit/vendor/pypi-watchfiles/snapshot/pypi-watchfiles-2024-07-03-23-17-56.tar.xz
Summary  : Simple, modern and high performance file watching and code reload in python.
Group    : Development/Tools
License  : Apache-2.0 CC0-1.0 ISC MIT Unicode-DFS-2016 Unlicense
Requires: pypi-watchfiles-bin = %{version}-%{release}
Requires: pypi-watchfiles-license = %{version}-%{release}
Requires: pypi-watchfiles-python = %{version}-%{release}
Requires: pypi-watchfiles-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(maturin)
BuildRequires : pypi-maturin
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# watchfiles
[![CI](https://github.com/samuelcolvin/watchfiles/workflows/ci/badge.svg?event=push)](https://github.com/samuelcolvin/watchfiles/actions?query=event%3Apush+branch%3Amain+workflow%3Aci)
[![Coverage](https://codecov.io/gh/samuelcolvin/watchfiles/branch/main/graph/badge.svg)](https://codecov.io/gh/samuelcolvin/watchfiles)
[![pypi](https://img.shields.io/pypi/v/watchfiles.svg)](https://pypi.python.org/pypi/watchfiles)
[![CondaForge](https://img.shields.io/conda/v/conda-forge/watchfiles.svg)](https://anaconda.org/conda-forge/watchfiles)
[![license](https://img.shields.io/github/license/samuelcolvin/watchfiles.svg)](https://github.com/samuelcolvin/watchfiles/blob/main/LICENSE)

%package bin
Summary: bin components for the pypi-watchfiles package.
Group: Binaries
Requires: pypi-watchfiles-license = %{version}-%{release}

%description bin
bin components for the pypi-watchfiles package.


%package license
Summary: license components for the pypi-watchfiles package.
Group: Default

%description license
license components for the pypi-watchfiles package.


%package python
Summary: python components for the pypi-watchfiles package.
Group: Default
Requires: pypi-watchfiles-python3 = %{version}-%{release}

%description python
python components for the pypi-watchfiles package.


%package python3
Summary: python3 components for the pypi-watchfiles package.
Group: Default
Requires: python3-core
Provides: pypi(watchfiles)
Requires: pypi(anyio)

%description python3
python3 components for the pypi-watchfiles package.


%prep
%setup -q -n watchfiles-0.22.0
cd %{_builddir}
tar xf %{_sourcedir}/pypi-watchfiles-2024-07-03-23-17-56.tar.xz
cd %{_builddir}/watchfiles-0.22.0
mkdir -p ./vendor
cp -r %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/* %{_builddir}/watchfiles-0.22.0/./vendor
mkdir -p .cargo
echo '[source.crates-io]' >> .cargo/config.toml
echo 'replace-with = "vendored-sources"' >> .cargo/config.toml
echo '[source.vendored-sources]' >> .cargo/config.toml
echo 'directory = "vendor"' >> .cargo/config.toml

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1720048843
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-watchfiles
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/autocfg/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/autocfg/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/e6d32072ef5f584a805b429ecbd4eec428316dde || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/bitflags-1.3.2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/bitflags-1.3.2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/bitflags/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/bitflags/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/cc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/cc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/cfg-if/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/cfg-if/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/crossbeam-channel/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/crossbeam-channel/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/crossbeam-utils/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/crossbeam-utils/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/144111aa0f14ef5a181326683aa9ebbd9252bca6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/filetime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/filetime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/3b042d3d971924ec0296687efd50dbe08b734976 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/fsevent-sys/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/50eaa7c436d7e44988ee682051992fa0600966dd || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/heck/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/heck/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/60c3522081bf15d7ac1d4c5a63de425ef253e87a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/indoc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/indoc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/inotify-sys/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/f3b0197751808b8dbd31f85c64f9ebd011c4d0f5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/inotify/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/1ae671f98444c3acb906a48b5c3640a28daf8de8 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/kqueue-sys/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/2b67e4761e0450300138e6bcf15a431f60ba5c6b || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/kqueue/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/2b67e4761e0450300138e6bcf15a431f60ba5c6b || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/libc/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/libc/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/36d69bcb88153a640740000efe933b009420ce7e || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/lock_api/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/lock_api/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/log/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/log/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9f3c36d2b7d381d9cf382a00166f3fbd06783636 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/memoffset/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/02bf11a87b9bbacedf2fcf4856af3b933faef82e || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/mio/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/27541df8e6d877c3912bbe4c48711f36e826cc5b || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/notify/LICENSE-CC0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/f44613dc75210fec09be69f474edcf7cd94fe7a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/once_cell/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/once_cell/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/parking_lot/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/parking_lot/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/parking_lot_core/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/parking_lot_core/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/portable-atomic/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/598f87f072f66e2269dd6919292b2934dbb20492 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/portable-atomic/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/proc-macro2/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/proc-macro2/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-build-config/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-build-config/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-ffi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-ffi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-macros-backend/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-macros-backend/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-macros/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3-macros/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3/pyo3-runtime/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/pyo3/pyo3-runtime/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/python3-dll-a/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/dc343e169fac680f93f90bc6cc63ca0c7a460131 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/quote/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/quote/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/redox_syscall-0.4.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/redox_syscall/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a00165152c82ea55b9fc254890dc8860c25e3bb6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/same-file/COPYING %{buildroot}/usr/share/package-licenses/pypi-watchfiles/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/same-file/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/same-file/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/scopeguard/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/scopeguard/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/f498d95a48889a0b1432e420e6754881eff1d593 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/smallvec/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/smallvec/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/c61640f6c218caf86d1b8072e09668a8362dba04 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/syn/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/syn/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/target-lexicon/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/unicode-ident/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/unicode-ident/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/unicode-ident/LICENSE-UNICODE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/583a5eebcf6119730bd96922e8a0faecf7faf720 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/unindent/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/unindent/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/walkdir/COPYING %{buildroot}/usr/share/package-licenses/pypi-watchfiles/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/walkdir/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/4c8990add9180fc59efa5b0d8faf643c9709501e || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/walkdir/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/wasi/LICENSE-APACHE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/wasi/LICENSE-Apache-2.0_WITH_LLVM-exception %{buildroot}/usr/share/package-licenses/pypi-watchfiles/f137043e018f2024e0414a9153ea728c203ae8e5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/wasi/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/winapi-util/COPYING %{buildroot}/usr/share/package-licenses/pypi-watchfiles/dd445710e6e4caccc4f8a587a130eaeebe83f6f6 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/winapi-util/LICENSE-MIT %{buildroot}/usr/share/package-licenses/pypi-watchfiles/2ad1215c12bd0a3492399dc438aa63084323c662 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/winapi-util/UNLICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-sys-0.48.0/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-sys-0.48.0/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-sys/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-sys/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-targets-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-targets-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-targets/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows-targets/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_aarch64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_i686_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnu-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnu-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnu/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnu/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnullvm-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnullvm-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnullvm/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_gnullvm/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_msvc-0.48.5/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_msvc-0.48.5/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_msvc/license-apache-2.0 %{buildroot}/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994 || :
cp %{_builddir}/pypi-watchfiles-2024-07-03-23-17-56/windows_x86_64_msvc/license-mit %{buildroot}/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301 || :
cp %{_builddir}/watchfiles-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-watchfiles/960803854a03fddb76107e327dd15352d761cf5e || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/watchfiles

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-watchfiles/02bf11a87b9bbacedf2fcf4856af3b933faef82e
/usr/share/package-licenses/pypi-watchfiles/144111aa0f14ef5a181326683aa9ebbd9252bca6
/usr/share/package-licenses/pypi-watchfiles/1ae671f98444c3acb906a48b5c3640a28daf8de8
/usr/share/package-licenses/pypi-watchfiles/27541df8e6d877c3912bbe4c48711f36e826cc5b
/usr/share/package-licenses/pypi-watchfiles/2ad1215c12bd0a3492399dc438aa63084323c662
/usr/share/package-licenses/pypi-watchfiles/2b67e4761e0450300138e6bcf15a431f60ba5c6b
/usr/share/package-licenses/pypi-watchfiles/36d69bcb88153a640740000efe933b009420ce7e
/usr/share/package-licenses/pypi-watchfiles/3b042d3d971924ec0296687efd50dbe08b734976
/usr/share/package-licenses/pypi-watchfiles/4c8990add9180fc59efa5b0d8faf643c9709501e
/usr/share/package-licenses/pypi-watchfiles/50eaa7c436d7e44988ee682051992fa0600966dd
/usr/share/package-licenses/pypi-watchfiles/5798832c31663cedc1618d18544d445da0295229
/usr/share/package-licenses/pypi-watchfiles/583a5eebcf6119730bd96922e8a0faecf7faf720
/usr/share/package-licenses/pypi-watchfiles/598f87f072f66e2269dd6919292b2934dbb20492
/usr/share/package-licenses/pypi-watchfiles/5bb5828e544f63bd76c1b7112981a1ad86ae77f9
/usr/share/package-licenses/pypi-watchfiles/60c3522081bf15d7ac1d4c5a63de425ef253e87a
/usr/share/package-licenses/pypi-watchfiles/689ec0681815ecc32bee639c68e7740add7bd301
/usr/share/package-licenses/pypi-watchfiles/6e5c4711bcae04967d7f5b5e01cf56ae03bebe7a
/usr/share/package-licenses/pypi-watchfiles/959ce149b1615b8bff3437f59282396756987859
/usr/share/package-licenses/pypi-watchfiles/960803854a03fddb76107e327dd15352d761cf5e
/usr/share/package-licenses/pypi-watchfiles/9a2b6b4ad55ec42cf19fc686c74668d3a6303ae7
/usr/share/package-licenses/pypi-watchfiles/9f3c36d2b7d381d9cf382a00166f3fbd06783636
/usr/share/package-licenses/pypi-watchfiles/a00165152c82ea55b9fc254890dc8860c25e3bb6
/usr/share/package-licenses/pypi-watchfiles/a3b3a65335e78bde163f84d599fa899776552994
/usr/share/package-licenses/pypi-watchfiles/c61640f6c218caf86d1b8072e09668a8362dba04
/usr/share/package-licenses/pypi-watchfiles/ce3a2603094e799f42ce99c40941544dfcc5c4a5
/usr/share/package-licenses/pypi-watchfiles/dc343e169fac680f93f90bc6cc63ca0c7a460131
/usr/share/package-licenses/pypi-watchfiles/dd445710e6e4caccc4f8a587a130eaeebe83f6f6
/usr/share/package-licenses/pypi-watchfiles/e6d32072ef5f584a805b429ecbd4eec428316dde
/usr/share/package-licenses/pypi-watchfiles/f137043e018f2024e0414a9153ea728c203ae8e5
/usr/share/package-licenses/pypi-watchfiles/f3b0197751808b8dbd31f85c64f9ebd011c4d0f5
/usr/share/package-licenses/pypi-watchfiles/f44613dc75210fec09be69f474edcf7cd94fe7a5
/usr/share/package-licenses/pypi-watchfiles/f498d95a48889a0b1432e420e6754881eff1d593
/usr/share/package-licenses/pypi-watchfiles/ff007ce11f3ff7964f1a5b04202c4e95b5c82c85

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
